//
//  STHorizontalPickerScaleDecimal.m
//  STHorizontalPickerScaleDecimal
//
//  Created by Wendy Kutschke on 6/1/13
//  Copyright 2013 Wendy Kutschke
//  This code was generated by Opacity. You may use or modify it in any way.
//

#include "STHorizontalPickerScaleDecimal.h"

#include <CoreText/CoreText.h>

@implementation STHorizontalPickerScaleDecimal


@end
