//
//  STHorizontalPickerScaleDecimal.h
//  STHorizontalPickerScaleDecimal
//
//  Created by Wendy Kutschke on 6/1/13
//  Copyright 2013 Wendy Kutschke
//  This code was generated by Opacity. You may use or modify it in any way.
//

#include <QuartzCore/QuartzCore.h>

extern const CGFloat kSTHorizontalPickerScaleDecimalWidth;
extern const CGFloat kSTHorizontalPickerScaleDecimalHeight;

@interface STHorizontalPickerScaleDecimal : CALayer

@property (nonatomic) CGColorRef scaleColor;
@property (nonatomic) CFStringRef primaryLabel;
@property (nonatomic) CGColorRef labelColor;

@end
